- name: Get IP Address and FQDN of the server
  hosts: localhost
  gather_facts: false

 

  tasks:
    - name: Retrieve IP Address
      ansible.builtin.command: hostname -I
      register: ip_address_output

 

    - name: Extract IP Address
      set_fact:
        ip_address: "{{ ip_address_output.stdout.split()[0] }}"

 

    - name: Retrieve FQDN
      ansible.builtin.command: hostname -f
      register: fqdn_output

 

    - name: Extract FQDN
      set_fact:
        fqdn: "{{ fqdn_output.stdout }}"

 

    - name: Display IP Address and FQDN
      debug:
        msg: "IP Address: {{ ip_address }}, FQDN: {{ fqdn }}"